# Generated by Django 4.0.1 on 2022-01-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
